version: '3'
services:
  ovehub-ove-service-imagetiles:
    image: ovehub/ove-service-imagetiles:${SERVICE_VERSION}
    build: 
      context: ../
      dockerfile: ove-service-imagetiles/Dockerfile
    ports:
    - "8182:8182"
    environment:
      s3Client__AccessKey: ""
      s3Client__Secret: ""
      s3Client__ServiceURL: ""
      AssetManagerHostUrl: ""
      ServiceHostUrl: ""
